### ISSUE TITLE
Reqs should get into log and reports

### ISSUE THREAD

**Issue by okt-kostik** [oktetlabs/test-environment#49]
We have a problem in Bublik (https://ts-factory.io)

Say I want to add a requirement FOO to tests and run full suite (i.e. both FOO and non-FOO tests). But I would like to see it in the UI and right now it has no chance to get into the DB. It's not part of the picture at all.

Tester logs reqs that were specified before the test, but we don't log reqs.

I suggest we log them for every iteration and include in the XML filter that will be passed into bublik during import.

**Comment by ol-arteman** [comment]
Implemented in https://github.com/oktetlabs/test-environment/commit/29b8d35116ea75a3ded24e60dfa9e0d272958d95 (v1.41.0)

**Comment by ol-andrewr** [comment]
done
