### ISSUE TITLE
It should be possible to have description of session/run

### ISSUE THREAD

**Issue by okt-kostik** [oktetlabs/test-environment#50]
Description is very useful and looks super nice in bublik

<img width="1111" alt="image" src="https://github.com/user-attachments/assets/5e866b6e-a2a2-4b77-af4b-3a5b00820be4">

thanks for adding it. Said that we can't specify it for runs and session. Thus it leads to empty descriptions (see above).

I think it should be trivial to support description all over the place. Please help

**Comment by okt-kostik** [comment]
Let's call it objective. I think description is the name used in the package.

I think we should keep it simple:

 - run with objective overrides script

**Comment by ol-dmitryiz** [comment]
It appears we already have <description> and <objective> tags in package.xml. <description> can be used in <package>, however contents is saved in pkg->objective. <objective> can be used in <script> and is parsed into script->objective. In log.xml they both go to <objective> tag.

However if I try to set <script>/<objective> in package.xml to something different than what is written under “@objective” in test C file, complaint is printed in log: “Inconsistency in test 'ip4_raw_send' objective from package.xml and tests-info.xml”. And still content from “@objective” is used. This is easy to fix in Tester.

Only for <session> we have neither <description> nor <objective>.

**Comment by okt-kostik** [comment]
We do have description and objective, but they can't be specified for run and session, right?

Only package and script.

**Comment by ol-dmitryiz** [comment]
For `<run>` we do not have it and I doubt we should. It seems enough to add `<objective>` (or `<description>`) for `<session>` - the only remaining thing which can be found inside `<run>` and does not have such tag yet.

**Comment by ol-andrewr** [comment]
Unfortunately not. Sometimes different runs are used for the same script and it is desirable to highlight particular run specific objective. It should override script/session objective.

**Comment by ol-dmitryiz** [comment]
You will be able to specify different objective in every `<script>` inside `<run>`. These will be different `<script>` tags inside different `<run>` tags.

**Comment by ol-andrewr** [comment]
OK

**Comment by ol-andrewr** [comment]
Done in:
commit af863cf9ca3fa3bf5a7c2811a963a42b7cce2f75
commit 4cbbcd4111ce04f8f22c1a273dcbbf32d2d16ed8
commit a9c147753761539306c35fef3f3fc8bf9dee4673
